site_name: ğŸº Boozer API Documentation
docs_dir: docs/
theme:
  name: mkdocs
  color_mode: dark
nav:
  - Home: index.md
  - Backend: backend.md
  - Database: db.md
  - Frontend: frontend.md
repo_url: https://github.com/03y/boozer/
